# IMAGE VARIABLES
NUM_CHANNELS = 3  # RGB images
PIXEL_DEPTH = 255
IMAGE_WIDTH = 400
IMAGE_HEIGHT = 400

# MODELS
FULL_CNN = False
TRANSFORMERS = False # MAIN FOR TRANSFORMERS
TRANSFER = True

# RUN VARIABLES
TRAIN_MODELS = True
SUBMISSION = True
LEARNING_RATE = 1e-5
PATCH_SIZE = 16
NUM_LABELS = 2
NUM_EPOCHS = 1
BATCH_SIZE = 16
TRAIN_TEST_SPLIT_RATIO = 0.8

# CONSTANTS FOR TRAINING
LEARNING_RATE_ENCODER = 1e-4
LEARNING_RATE_DECODER = 1e-3
LEARNING_RATE_SEGMENTATION = 1e-3
DEFAULT_GAMMA = 0.1
DEFAULT_STEP = 1
PLOT_DATASET = False

# PREPROCESSING VARIABLES
TRANSFORM_PROBABILITY = 0.5
SAMPLES_PER_IMAGE = 1
DATA_AUGMENTATION = True
VAR_AUGMENTATION=True
LEARNING_RATE_ = False
NORMALIZE = False
BALANCE = False

# RANDOM TRANSFORMS PROBABILITIES AND VALUES
HORIZONTAL_FLIP_PROBABILITY = 0.5
VERTICAL_FLIP_PROBABILITY = 0.5
CHANNEL_PERM_PROBABILITY = 0.5
BLUR_PROBABILITY = 0.4
BRIGHTNESS = 0.2
CONTRAST = 0.2
SATURATION = 0.2
HUE = 0.1

#FULL_CNN
FULL_CNN_FEATURES = [64, 128, 256, 512, 1024, 2048]

### THIS HAS BEEN GIVEN DO NOT CHANGE ###
FOREGROUND_THRESHOLD = 0.25 # percentage of pixels > 1 required to assign a foreground label to a patch

